name: UI Tests on Emulator (Kaspresso)

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'

  ANDROID_PROFILE: pixel
  ANDROID_TARGET: google_apis
  ANDROID_API_LEVEL: 30 
  ANDROID_ARCH: x86_64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  kaspresso-instrumentation-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Start Android Emulator and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          disable-animations: true 
          script: |
            chmod +x ./gradlew
            ./gradlew connectedDebugAndroidTest

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: app/build/outputs/allure-results
