name: Android UI Tests with Kaspresso

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: '17'
  ANDROID_API_LEVEL: 31
  ANDROID_TARGET: google_apis
  ANDROID_ARCH: x86_64
  ANDROID_PROFILE: pixel
  ARTIFACT_NAME: allure-results

defaults:
  run:
    shell: bash

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
            
      - name: Run UI tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          script: |
            echo "📱 Ждём подключение эмулятора..."
            adb wait-for-device

            echo "📦 Проверим видимость instrumentation:"
            adb shell pm list instrumentation | tee instrumentation.txt

            echo "📁 Проверим, собрался ли тестовый APK:"
            ls -la app/build/outputs/apk/androidTest/debug/ > apks.txt || echo "❌ APK не найден"

            echo "🧾 Проверим AndroidManifest.xml из androidTest:"
            cat app/build/outputs/apk/androidTest/debug/AndroidManifest.xml | head -n 50 > manifest.txt || echo "❌ Manifest не найден"

            echo "🧘‍♂️ Отключаем анимации:"
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0

            echo "🚀 Запускаем тесты:"
            ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunner=com.kaspersky.kaspresso.runner.KaspressoRunner --stacktrace --info

      - name: Upload debug info
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-info
          path: |
            instrumentation.txt
            apks.txt
            manifest.txt

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: app/build/reports/allure-results/
