name: Android UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Android Emulator
        run: |
         sdkmanager "system-images;android-30;google_apis;x86_64"
         echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
         emulator -avd test -no-audio -no-window -gpu off &
         adb wait-for-device
         adb shell settings put global window_animation_scale 0
         adb shell settings put global transition_animation_scale 0
         adb shell settings put global animator_duration_scale 0
         adb shell input keyevent 82 &
          

      - name: Run UI tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Pull Allure results from device
        run: ./gradlew pullAllureResults

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: app/build/allure-results
